import type { PostTemplate } from "@/lib/types";

export const TEMPLATE_PRESETS: PostTemplate[] = [
  {
    id: "preset-market-pulse",
    name: "Market Pulse & Finance",
    ratio: "1:1",
    width: 1200,
    height: 1200,
    backgroundType: "gradient",
    backgroundGradient: "linear-gradient(135deg, #090d16 0%, #111a2e 50%, #062b24 100%)",
    overlayOpacity: 0.15,
    category: "Finance & Business",
    textElements: [
      {
        id: "badge",
        type: "badge",
        text: "MARKET INSIGHT • 2026",
        fontSize: 24,
        fontWeight: "bold",
        fontFamily: "Outfit",
        color: "#34d399",
        align: "left",
        yOffset: 12,
        showBackgroundPill: true,
        pillColor: "rgba(52, 211, 153, 0.15)",
      },
      {
        id: "headline",
        type: "headline",
        text: "3 Smart Moves Before The Next Market Cycle",
        fontSize: 68,
        fontWeight: "800",
        fontFamily: "Inter",
        color: "#ffffff",
        align: "left",
        yOffset: 25,
      },
      {
        id: "subtext",
        type: "subtext",
        text: "Simple risk-management strategies smart investors use to protect capital and seize high-probability trends.",
        fontSize: 32,
        fontWeight: "normal",
        fontFamily: "Inter",
        color: "#94a3b8",
        align: "left",
        yOffset: 58,
      },
      {
        id: "footer",
        type: "footer",
        text: "@YourBrand • Save & Follow for daily financial updates",
        fontSize: 24,
        fontWeight: "600",
        fontFamily: "Inter",
        color: "#64748b",
        align: "left",
        yOffset: 88,
      },
    ],
  },
  {
    id: "preset-actionable-tip",
    name: "Actionable Daily Tip",
    ratio: "4:5",
    width: 1080,
    height: 1350,
    backgroundType: "gradient",
    backgroundGradient: "linear-gradient(180deg, #18181b 0%, #0f172a 60%, #1e1b4b 100%)",
    overlayOpacity: 0.2,
    category: "Productivity & Growth",
    textElements: [
      {
        id: "badge",
        type: "badge",
        text: "🔥 QUICK TIP OF THE DAY",
        fontSize: 26,
        fontWeight: "bold",
        fontFamily: "Outfit",
        color: "#fbbf24",
        align: "center",
        yOffset: 14,
        showBackgroundPill: true,
        pillColor: "rgba(251, 191, 36, 0.18)",
      },
      {
        id: "headline",
        type: "headline",
        text: "Stop Wasting 2 Hours Every Morning",
        fontSize: 64,
        fontWeight: "800",
        fontFamily: "Outfit",
        color: "#ffffff",
        align: "center",
        yOffset: 26,
      },
      {
        id: "subtext",
        type: "subtext",
        text: "The 3-minute evening shutdown ritual that top performers use to wake up with instant clarity and unstoppable momentum.",
        fontSize: 32,
        fontWeight: "normal",
        fontFamily: "Inter",
        color: "#cbd5e1",
        align: "center",
        yOffset: 52,
      },
      {
        id: "footer",
        type: "footer",
        text: "💬 Drop your morning routine in comments below!",
        fontSize: 26,
        fontWeight: "bold",
        fontFamily: "Inter",
        color: "#60a5fa",
        align: "center",
        yOffset: 86,
      },
    ],
  },
  {
    id: "preset-breaking-news",
    name: "Breaking Announcement",
    ratio: "1.91:1",
    width: 1200,
    height: 630,
    backgroundType: "gradient",
    backgroundGradient: "linear-gradient(135deg, #1e1b4b 0%, #311042 50%, #4c0519 100%)",
    overlayOpacity: 0.15,
    category: "News & Alerts",
    textElements: [
      {
        id: "badge",
        type: "badge",
        text: "OFFICIAL ANNOUNCEMENT",
        fontSize: 22,
        fontWeight: "bold",
        fontFamily: "Outfit",
        color: "#f43f5e",
        align: "left",
        yOffset: 15,
        showBackgroundPill: true,
        pillColor: "rgba(244, 63, 94, 0.2)",
      },
      {
        id: "headline",
        type: "headline",
        text: "Big Updates Are Rolling Out This Week",
        fontSize: 54,
        fontWeight: "800",
        fontFamily: "Inter",
        color: "#ffffff",
        align: "left",
        yOffset: 32,
      },
      {
        id: "subtext",
        type: "subtext",
        text: "Here is everything you need to know about our upcoming release and new features.",
        fontSize: 26,
        fontWeight: "normal",
        fontFamily: "Inter",
        color: "#e2e8f0",
        align: "left",
        yOffset: 65,
      },
      {
        id: "footer",
        type: "footer",
        text: "Read more details in caption ⬇️",
        fontSize: 20,
        fontWeight: "600",
        fontFamily: "Inter",
        color: "#fb7185",
        align: "left",
        yOffset: 86,
      },
    ],
  },
  {
    id: "preset-leadership-quote",
    name: "Thought Leadership Quote",
    ratio: "1:1",
    width: 1200,
    height: 1200,
    backgroundType: "gradient",
    backgroundGradient: "linear-gradient(145deg, #0f172a 0%, #1e1b4b 60%, #2e1065 100%)",
    overlayOpacity: 0.2,
    category: "Inspiration & Quotes",
    textElements: [
      {
        id: "badge",
        type: "badge",
        text: "“ INSIGHT",
        fontSize: 32,
        fontWeight: "bold",
        fontFamily: "Merriweather",
        color: "#a855f7",
        align: "center",
        yOffset: 16,
      },
      {
        id: "headline",
        type: "headline",
        text: "Simplicity is the ultimate sophistication. When in doubt, eliminate the unnecessary.",
        fontSize: 56,
        fontWeight: "600",
        fontFamily: "Merriweather",
        color: "#f8fafc",
        align: "center",
        yOffset: 34,
      },
      {
        id: "subtext",
        type: "subtext",
        text: "Most people fail not because their goals are too ambitious, but because their focus is diluted.",
        fontSize: 28,
        fontWeight: "normal",
        fontFamily: "Inter",
        color: "#94a3b8",
        align: "center",
        yOffset: 66,
      },
      {
        id: "footer",
        type: "footer",
        text: "Share this if you needed to hear this today",
        fontSize: 22,
        fontWeight: "bold",
        fontFamily: "Inter",
        color: "#c084fc",
        align: "center",
        yOffset: 88,
      },
    ],
  },
  {
    id: "preset-story-hook",
    name: "Full-Screen Story Hook",
    ratio: "9:16",
    width: 1080,
    height: 1920,
    backgroundType: "gradient",
    backgroundGradient: "linear-gradient(180deg, #09090b 0%, #1e293b 50%, #0369a1 100%)",
    overlayOpacity: 0.25,
    category: "Story & Reel",
    textElements: [
      {
        id: "badge",
        type: "badge",
        text: "WAIT BEFORE YOU SCROLL",
        fontSize: 30,
        fontWeight: "800",
        fontFamily: "Outfit",
        color: "#38bdf8",
        align: "center",
        yOffset: 18,
        showBackgroundPill: true,
        pillColor: "rgba(56, 189, 248, 0.2)",
      },
      {
        id: "headline",
        type: "headline",
        text: "Here Are 3 Things Nobody Tells You About Growth",
        fontSize: 72,
        fontWeight: "800",
        fontFamily: "Outfit",
        color: "#ffffff",
        align: "center",
        yOffset: 32,
      },
      {
        id: "subtext",
        type: "subtext",
        text: "Consistency is boring, but compound results are miraculous. Keep going even when nobody is watching.",
        fontSize: 36,
        fontWeight: "normal",
        fontFamily: "Inter",
        color: "#cbd5e1",
        align: "center",
        yOffset: 56,
      },
      {
        id: "footer",
        type: "footer",
        text: "👉 Tap link in bio for full playbook",
        fontSize: 30,
        fontWeight: "bold",
        fontFamily: "Inter",
        color: "#7dd3fc",
        align: "center",
        yOffset: 84,
      },
    ],
  },
  {
    id: "preset-minimal-clean",
    name: "Minimalist Editorial Card",
    ratio: "1:1",
    width: 1200,
    height: 1200,
    backgroundType: "gradient",
    backgroundGradient: "linear-gradient(135deg, #f8fafc 0%, #e2e8f0 100%)",
    overlayOpacity: 0.05,
    category: "Minimalist",
    textElements: [
      {
        id: "badge",
        type: "badge",
        text: "PERSPECTIVE",
        fontSize: 22,
        fontWeight: "bold",
        fontFamily: "Outfit",
        color: "#475569",
        align: "left",
        yOffset: 16,
        showBackgroundPill: true,
        pillColor: "rgba(100, 116, 139, 0.15)",
      },
      {
        id: "headline",
        type: "headline",
        text: "Focus on Direction, Not Speed.",
        fontSize: 72,
        fontWeight: "800",
        fontFamily: "Inter",
        color: "#0f172a",
        align: "left",
        yOffset: 30,
      },
      {
        id: "subtext",
        type: "subtext",
        text: "Running fast in the wrong direction gets you nowhere. Measure clarity before velocity.",
        fontSize: 34,
        fontWeight: "normal",
        fontFamily: "Inter",
        color: "#334155",
        align: "left",
        yOffset: 60,
      },
      {
        id: "footer",
        type: "footer",
        text: "Save this post to remind yourself later.",
        fontSize: 24,
        fontWeight: "600",
        fontFamily: "Inter",
        color: "#64748b",
        align: "left",
        yOffset: 86,
      },
    ],
  },
];

export const GRADIENT_PRESETS = [
  { name: "Obsidian Slate", value: "linear-gradient(135deg, #090d16 0%, #111a2e 50%, #062b24 100%)" },
  { name: "Midnight Violet", value: "linear-gradient(145deg, #0f172a 0%, #1e1b4b 60%, #2e1065 100%)" },
  { name: "Solar Amber", value: "linear-gradient(135deg, #1c1917 0%, #291a0c 50%, #78350f 100%)" },
  { name: "Emerald Cyber", value: "linear-gradient(135deg, #022c22 0%, #064e3b 50%, #047857 100%)" },
  { name: "Crimson Velvet", value: "linear-gradient(135deg, #1e1b4b 0%, #311042 50%, #4c0519 100%)" },
  { name: "Deep Ocean", value: "linear-gradient(180deg, #09090b 0%, #1e293b 50%, #0369a1 100%)" },
  { name: "Clean Paper", value: "linear-gradient(135deg, #f8fafc 0%, #e2e8f0 100%)" },
  { name: "Dark Neutral", value: "linear-gradient(135deg, #18181b 0%, #27272a 100%)" },
];
